force-app/main/default/objects/Federal_Tax_Bracket__mdt/Federal_Tax_Bracket__mdt.object-meta.xml
<CustomObject>
    <description>USA Federal tax brackets and income tax rates to ease tax calculations.
To fill out this data use Tax and Earned Income Credit Tables from the Instructions for Form 1040.</description>
    <label>Federal Tax Bracket</label>
    <pluralLabel>Federal Tax Brackets</pluralLabel>
</CustomObject>

force-app/main/default/objects/Federal_Tax_Bracket__mdt/fields/Calculation_order__c.field-meta.xml
<CustomField>
    <fullName>Calculation_order__c</fullName>
    <description>Auxiliary field for ordering records before calculations.</description>
    <label>Calculation order</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Federal_Tax_Bracket__mdt/fields/Filing_status__c.field-meta.xml
<CustomField>
    <fullName>Filing_status__c</fullName>
    <description>Tax filing status value. Uses in the &apos;Take-Home Pay Estimator&apos; calculator.</description>
    <label>Filing status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Single</fullName>
                <default>true</default>
                <label>Single</label>
            </value>
            <value>
                <fullName>MarriedFJointly</fullName>
            </value>
            <value>
                <fullName>MarriedFSeparately</fullName>
            </value>
            <value>
                <fullName>HeadOfHousehold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Federal_Tax_Bracket__mdt/fields/Min_Bracket__c.field-meta.xml
<CustomField>
    <fullName>Min_Bracket__c</fullName>
    <description>The minimum value of the bracket that determines the tax rate.</description>
    <label>Min Bracket</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Federal_Tax_Bracket__mdt/fields/Tax_Rate__c.field-meta.xml
<CustomField>
    <fullName>Tax_Rate__c</fullName>
    <description>Federal tax rate that applies to the specified filing status and brackets.</description>
    <label>Tax Rate</label>
    <precision>5</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Federal_Tax_Bracket__mdt/fields/Tax_Value__c.field-meta.xml
<CustomField>
    <fullName>Tax_Value__c</fullName>
    <description>Predefined tax value for the low bracket value.</description>
    <label>Tax Value</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tax_Deduction__mdt/Tax_Deduction__mdt.object-meta.xml
<CustomObject>
    <description>Contains the values ​​of new tax deductions, federal and state.</description>
    <label>Tax Deduction</label>
    <pluralLabel>Tax Deductions</pluralLabel>
</CustomObject>

force-app/main/default/objects/Tax_Deduction__mdt/fields/Deduction__c.field-meta.xml
<CustomField>
    <fullName>Deduction__c</fullName>
    <description>Deduction value depending on the filing status.</description>
    <label>Deduction</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tax_Deduction__mdt/fields/isFederal__c.field-meta.xml
<CustomField>
    <fullName>isFederal__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If this checkbox is checked then the values are considered as the Federal Standard Deduction.</description>
    <label>isFederal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TakeHomePayEstimatorController.cls
public with sharing class TakeHomePayEstimatorController {

    @AuraEnabled(cacheable=true)
    public static Decimal getTaxDeduction(String filingStatus, Boolean isFederal) {
        List<Tax_Deduction__mdt> taxDeductions = [
            SELECT
                Filing_status__c,
                isFederal__c,
                Deduction__c
            FROM Tax_Deduction__mdt
            WHERE isFederal__c = :isFederal
            AND Filing_status__c = :filingStatus
        ];
        if (taxDeductions.size() > 0) {
            return taxDeductions[0].Deduction__c;
        } else {
            throw new AuraHandledException('Tax Deductions are not specified!');
        }
    }

    @AuraEnabled(cacheable=true)
    public static List<Federal_Tax_Bracket__mdt> getTaxBrackets(String filingStatus) {
        List<Federal_Tax_Bracket__mdt> taxBrackets = [
            SELECT
                Filing_status__c,
                Min_Bracket__c,
                Tax_Rate__c,
                Tax_Value__c,
                Calculation_order__c
            FROM Federal_Tax_Bracket__mdt
            WHERE Filing_status__c = :filingStatus
            ORDER BY Calculation_order__c ASC
        ];
        if (taxBrackets.size() > 0) {
            return taxBrackets;
        } else {
            throw new AuraHandledException('Tax Brackets are not specified!');
        }
    }
}