force-app/main/default/objects/Federal_Tax_Bracket__mdt/Federal_Tax_Bracket__mdt.object-meta.xml
<CustomObject>
    <description>USA Federal tax brackets and income tax rates to ease tax calculations.
To fill out this data use Tax and Earned Income Credit Tables from the Instructions for Form 1040.</description>
    <label>Federal Tax Bracket</label>
    <pluralLabel>Federal Tax Brackets</pluralLabel>
</CustomObject>

force-app/main/default/objects/Federal_Tax_Bracket__mdt/fields/Filing_status__c.field-meta.xml
<CustomField>
    <fullName>Filing_status__c</fullName>
    <description>Tax filing status value. Uses in the &apos;Take-Home Pay Estimator&apos; calculator.</description>
    <label>Filing status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Single</fullName>
                <default>true</default>
                <label>Single</label>
            </value>
            <value>
                <fullName>MarriedFJointly</fullName>
            </value>
            <value>
                <fullName>MarriedFSeparately</fullName>
            </value>
            <value>
                <fullName>HeadOfHousehold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <description>Stores job applications on vacancies. Helps to log and manage the entire job application lifecycle.</description>
    <label>Job Application</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0}</displayFormat>
        <label>Job Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Annual_Take_home_Pay__c.field-meta.xml
<CustomField>
    <fullName>Annual_Take_home_Pay__c</fullName>
    <description>The estimated value of the annual Take-home Paycheck.</description>
    <label>Annual Take-home Pay</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Federal_Income_Tax__c.field-meta.xml
<CustomField>
    <fullName>Federal_Income_Tax__c</fullName>
    <description>The estimated value of the yearly tax liabilities.</description>
    <label>Federal Income Tax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Filing_status__c.field-meta.xml
<CustomField>
    <fullName>Filing_status__c</fullName>
    <description>The Tax Filing status for which the estimation was performed.</description>
    <label>Filing status</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Medicare_Withholding__c.field-meta.xml
<CustomField>
    <fullName>Medicare_Withholding__c</fullName>
    <description>The estimated yearly Medicare withholdings liability.</description>
    <label>Medicare Withholding</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Monthly_Take_home_Pay__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Take_home_Pay__c</fullName>
    <description>The estimated value of the monthly Take-home Paycheck.</description>
    <label>Monthly Take-home Pay</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Social_Security__c.field-meta.xml
<CustomField>
    <fullName>Social_Security__c</fullName>
    <description>The yearly Social Security liability.</description>
    <label>Social Security</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/TakeHomePayEstimatorControllerTest.cls
/**
* TakeHomePayEstimatorControllerTest class description:
*
* Test class for the classes TakeHomePayEstimatorController.
*
**/
@isTest
private class TakeHomePayEstimatorControllerTest {

    @isTest
    static void testGetTaxDeduction() {
        // Set test data
        Decimal taxDeduction;
        User stdUser = TestDataFactory.createUser('stuser');

        // Run test
        System.runAs(stdUser) {
            taxDeduction = TakeHomePayEstimatorController.getTaxDeduction('Single');
        }
        Assert.areEqual(14600.00, taxDeduction, 'Tax deduction does not match');
    }

    @isTest
    static void testgetTaxBrackets() {
        // Run Test
        Test.startTest();
        List<Federal_Tax_Bracket__mdt> taxBrackets = TakeHomePayEstimatorController.getTaxBrackets('Single');
        Test.stopTest();

        // Assert
        Assert.areEqual(7, taxBrackets.size(), 'Expected to get 7 Federal Tax Brackets');
    }

    @isTest
    static void testGetTaxesAndPayChecks() {
        // Set test data
        TakeHomePayWrapper wrapper = new TakeHomePayWrapper();
        wrapper.annualIncome = 100000.00;
        wrapper.filingStatus = 'Single';
        wrapper.taxableIncome = 85400.00;

        // Run Test
        Test.startTest();
        Map<String, Decimal> otherTaxes = TakeHomePayEstimatorController.getTaxesAndPayChecks(wrapper);
        Test.stopTest();

        // Assert
        Assert.areEqual(3, otherTaxes.size(), 'Expected to get 3 records of calculated taxes');
        // Assert calculated numbers
        Assert.areEqual(13840.78, otherTaxes.get('federalTaxValue'), 'Incorrect Federal Tax Value for the Single filing status');
        Assert.areEqual(1450.00, otherTaxes.get('medicare'), 'Incorrect Medicare Value for the Single filing status');
        Assert.areEqual(6200.00, otherTaxes.get('socialSecurity'), 'Incorrect Social Security Value');
    }

    @isTest
    static void testGetTaxesAndPayChecks_CheckSocialSecurity() {
        // Set test data
        TakeHomePayWrapper wrapper = new TakeHomePayWrapper();
        wrapper.annualIncome = 200000.00;
        wrapper.filingStatus = 'Single';
        wrapper.taxableIncome = 185400.00;

        // Run Test
        Test.startTest();
        Map<String, Decimal> otherTaxes = TakeHomePayEstimatorController.getTaxesAndPayChecks(wrapper);
        Test.stopTest();

        // Assert
        Assert.areEqual(3, otherTaxes.size(), 'Expected to get 3 records of calculated taxes');
        // Assert calculated numbers
        Assert.areEqual(10453.20, otherTaxes.get('socialSecurity'), 'Incorrect Social Security Value');
    }

    @isTest
    static void testupdateJobApplication() {
        // Set test data
        String filingStatus = 'Single';
        TakeHomePayWrapper wrapper = new TakeHomePayWrapper();
        wrapper.federalTaxValue = 13840.78;
        wrapper.socialSecurity = 6200.00;
        wrapper.medicare = 1450.00;
        wrapper.annualPaycheck = 78509.22;
        wrapper.monthlyPaycheck = 6542.44;
        Account acc = TestDataFactory.createAccount();
        Job_Application__c jobApp = TestDataFactory.createJobApplication(acc);
        
        // Run test
        Test.startTest();
        TakeHomePayEstimatorController.updateJobApplication(jobApp.Id, wrapper, filingStatus);
        Test.stopTest();

        // Assert
        Job_Application__c updatedJobApp = [
            SELECT
                Id,
                Federal_Income_Tax__c,
                Social_Security__c,
                Medicare_Withholding__c,
                Annual_Take_home_Pay__c,
                Monthly_Take_home_Pay__c,
                Filing_status__c
            FROM Job_Application__c
            WHERE Id = :jobApp.Id
        ];
        Assert.areEqual(wrapper.federalTaxValue, updatedJobApp.Federal_Income_Tax__c, 'Federal Tax Value does not match');
        Assert.areEqual(wrapper.socialSecurity, updatedJobApp.Social_Security__c, 'Social Security Tax Value does not match');
        Assert.areEqual(wrapper.medicare, updatedJobApp.Medicare_Withholding__c, 'Federal Tax Value does not match');
        Assert.areEqual(wrapper.annualPaycheck, updatedJobApp.Annual_Take_home_Pay__c, 'Federal Tax Value does not match');
        Assert.areEqual(wrapper.monthlyPaycheck, updatedJobApp.Monthly_Take_home_Pay__c, 'Federal Tax Value does not match');
        Assert.areEqual(filingStatus, updatedJobApp.Filing_status__c, 'Federal Tax Value does not match');
    }

    @isTest
    static void testupdateJobApplication_Exception() {
        // Set test data
        String filingStatus = 'Single';
        TakeHomePayWrapper wrapper = new TakeHomePayWrapper();
        wrapper.federalTaxValue = 13840.78;
        wrapper.socialSecurity = 6200.00;
        wrapper.medicare = 1450.00;
        wrapper.annualPaycheck = 78509.22;
        wrapper.monthlyPaycheck = 6542.44;
        Account acc = TestDataFactory.createAccount();
        Job_Application__c jobApp = TestDataFactory.createJobApplication(acc);
        User unauthUser = TestDataFactory.createUser('uauser');
        
        // Run test
        Test.startTest();
        try {
            System.runAs(unauthUser) {
                TakeHomePayEstimatorController.updateJobApplication(jobApp.Id, wrapper, filingStatus);
            } 
        } catch (Exception ex) {
            // Assert
            Assert.areEqual('System.AuraHandledException', ex.getTypeName(), 'Expected to get thrown AuraHandledException');
            Assert.areEqual('You can not update Job Application record', ex.getMessage(), 'Exception messages do not match');
        }
        Test.stopTest();
    }
}