force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <description>Stores job applications on vacancies. Helps to log and manage the entire job application lifecycle.</description>
    <label>Job Application</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0}</displayFormat>
        <label>Job Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Stores the name of the company where the job application is being sent.</description>
    <label>Company Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Follow_up_date__c.field-meta.xml
<CustomField>
    <fullName>Follow_up_date__c</fullName>
    <description>Specifies when to follow up on the application.</description>
    <label>Follow-up date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <description>User notes. It can hold a lot of information.</description>
    <label>Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Position_Title__c.field-meta.xml
<CustomField>
    <fullName>Position_Title__c</fullName>
    <description>Keeps track of the specific job title or position being applied for.</description>
    <label>Position/Title</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>This field will track the current status of the job application.</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saved</fullName>
                <default>true</default>
                <label>Saved</label>
            </value>
            <value>
                <fullName>Applying</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Interviewing</fullName>
            </value>
            <value>
                <fullName>Negotiating</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CleanUpStaleJobAppSchedulableTest.cls
/**
* CleanUpStaleJobAppSchedulableTest class description:
*
* Test class for the class CleanUpStaleJobApplicationsSchedulable.
*
**/
@isTest
private class CleanUpStaleJobAppSchedulableTest {

    @TestSetup
    static void makeTestData(){
        Account acc = TestDataFactory.createAccount();
        User stUser = TestDataFactory.createUser('stuser');
        List<Job_Application__c> jobApps = new List<Job_Application__c>();
        for (Integer i = 0; i < 5; i++) {
            String status = 'Saved';
            if (i == 4) {
                status = 'Accepted';
            }
            jobApps.add(new Job_Application__c(
                Position_Title__c = 'Test Position ' + i,
                Company_Name__c = acc.Id,
                OwnerId = stUser.Id,
                Follow_up_date__c = Date.today().addDays(-10 * i),
                Status__c = status
            ));
        }
        Database.insert(jobApps);
    }

    @isTest
    static void testStaleJobApps() {
        // Run test
        Test.startTest();
        CleanUpStaleJobApplicationsSchedulable scheduleJob = new CleanUpStaleJobApplicationsSchedulable();
        String year = String.valueOf(Date.today().addYears(1).year());
        String cronExp = '0 0 1 * * ? ' + year;
        System.schedule(
            'CleanUpStaleJobApplications', cronExp, scheduleJob
        );
        scheduleJob.execute(null);
        Test.stopTest();

        // Assert
        List<Job_Application__c> jobApps = [
            SELECT 
                Id,
                Position_Title__c,
                Follow_up_date__c,
                Status__c,
                Notes__c
            FROM Job_Application__c
        ];
        Assert.areEqual(5, jobApps.size(), 'Expected to get 5 Job Application records');
        for (Job_Application__c jobApp : jobApps) {
            if (jobApp.Position_Title__c == 'Test Position 3') {
                Assert.areEqual('Closed', jobApp.Status__c, 'Status should be changed to Closed');
                Assert.areEqual('The job application was closed by an automated process!', jobApp.Notes__c, 'Notes should be correctly populated');
            } else {
                Assert.isFalse(jobApp.Status__c == 'Closed', 'Status of not stale Job Apps and Accepted Job Apps should not be changed');
                Assert.isNull(jobApp.Notes__c, 'Notes should not be populated');
            }
        }
    }
}