force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <description>Stores job applications on vacancies. Helps to log and manage the entire job application lifecycle.</description>
    <label>Job Application</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0}</displayFormat>
        <label>Job Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>This field will track the current status of the job application.</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saved</fullName>
                <default>true</default>
                <label>Saved</label>
            </value>
            <value>
                <fullName>Applying</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Interviewing</fullName>
            </value>
            <value>
                <fullName>Negotiating</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Application_Task__mdt/Job_Application_Task__mdt.object-meta.xml
<CustomObject>
    <description>The list of possible Job Application Tasks depending on the current Status of the job application.</description>
    <label>Job Application Task</label>
    <pluralLabel>Job Application Tasks</pluralLabel>
</CustomObject>

force-app/main/default/objects/Job_Application_Task__mdt/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The Job Application Statuses. They group Tasks.</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saved</fullName>
                <default>true</default>
                <label>Saved</label>
            </value>
            <value>
                <fullName>Applying</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Interviewing</fullName>
            </value>
            <value>
                <fullName>Negotiating</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/JobApplicationTasksQueueableTest.cls
/**
* InterviewNotificationsBatchTest class description:
*
* Test class for the class InterviewNotificationsBatch.
*
**/
@isTest
private class JobApplicationTasksQueueableTest {

    @isTest
    static void testAddTasksByQueueableJob() {
        Account acc = TestDataFactory.createAccount();
        
        // Run Test
        Test.startTest();
        // Queueable Class runs by AfterInsert Trigger
        Job_Application__c jobApp = TestDataFactory.createJobApplication(acc);
        Test.stopTest();

        // Assert
        List<AsyncApexJob> apexJobs = [
            SELECT 
                Id 
            FROM AsyncApexJob
            WHERE JobType = 'Queueable'
        ];
        Assert.areEqual(1, apexJobs.size(), 'Expected 1 Queueable Job was run');
        // Validate that the job has run by verifying that the record was created.
        List<Task> createdTasks = [
            SELECT 
                Id,
                WhatId
            FROM Task
            WHERE WhatId = :jobApp.Id
        ];
        List<Job_Application_Task__mdt> taskParamsToCreate = [
            SELECT
                Id,
                Status__c 
            FROM Job_Application_Task__mdt 
            WHERE Status__c = 'Saved'
        ];
        Assert.areEqual(taskParamsToCreate.size(), createdTasks.size(), 'The number of created tasks must match the number of task params for the status');
    } 
}