force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <description>Stores job applications on vacancies. Helps to log and manage the entire job application lifecycle.</description>
    <label>Job Application</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0}</displayFormat>
        <label>Job Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Follow_up_date__c.field-meta.xml
<CustomField>
    <fullName>Follow_up_date__c</fullName>
    <description>Specifies when to follow up on the application.</description>
    <label>Follow-up date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <description>User notes. It can hold a lot of information.</description>
    <label>Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>This field will track the current status of the job application.</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saved</fullName>
                <default>true</default>
                <label>Saved</label>
            </value>
            <value>
                <fullName>Applying</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Interviewing</fullName>
            </value>
            <value>
                <fullName>Negotiating</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CleanUpStaleJobApplicationsSchedulable.cls
/**
* CleanUpStaleJobApplicationsSchedulable class description:
*
* Schedulable class that runs at a specified time to clean up stale Job Applications.
* Stale Criteria:
*   - Status is not Closed or Accepted
*   - Follow Date 30 days or more
*
**/
public with sharing class CleanUpStaleJobApplicationsSchedulable implements Schedulable {

    public void execute(SchedulableContext sc) {
        Set<String> statusesToIgnore = new Set<String>{'Closed', 'Accepted'};

        List<Job_Application__c> jobApps = [
            SELECT 
                Id,
                Status__c,
                Notes__c
            FROM Job_Application__c
            WHERE Follow_up_date__c <= N_DAYS_AGO:30
                AND Status__c NOT IN :statusesToIgnore
        ];

        if (jobApps.size() > 0) {
            for (Job_Application__c jobApp : jobApps) {
                jobApp.Status__c = 'Closed';
                jobApp.Notes__c = 'The job application was closed by an automated process!';
            }
            Database.update(jobApps);
        }
    }
}