force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <description>Stores job applications on vacancies. Helps to log and manage the entire job application lifecycle.</description>
    <label>Job Application</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0}</displayFormat>
        <label>Job Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Stores the name of the company where the job application is being sent.</description>
    <label>Company Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Represents the main point of contact for the job. This could be a recruiter or employee at the company.</description>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pivotal_Contact__c/Pivotal_Contact__c.object-meta.xml
<CustomObject>
    <description>Helps tracking of pivotal individuals associated with the job application, such as hiring managers, recruiters, and other relevant employees.</description>
    <label>Pivotal Contact</label>
    <nameField>
        <displayFormat>PC# {0}</displayFormat>
        <label>Pivotal Contact Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pivotal Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Pivotal_Contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>The Contact associated with the job application. This could be the hiring manager, recruiter, or other relevant employee.</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Relates to Job Applications</relationshipLabel>
    <relationshipName>Pivotal_Contacts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Pivotal_Contact__c/fields/Job_Application__c.field-meta.xml
<CustomField>
    <fullName>Job_Application__c</fullName>
    <description>Job Application to which contact is related.</description>
    <label>Job Application</label>
    <referenceTo>Job_Application__c</referenceTo>
    <relationshipLabel>Pivotal Contacts</relationshipLabel>
    <relationshipName>Pivotal_Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/JobApplicationTriggerHandler.cls
public with sharing class JobApplicationTriggerHandler extends TriggerHandler {

    private List<Job_Application__c> newJobApps;
    private Map<Id, Job_Application__c> newJobAppsMap;

    /**
     * Constructor. Set instance variables.
     */
    public JobApplicationTriggerHandler() {
        this.newJobApps = (List<Job_Application__c>) Trigger.new;
        this.newJobAppsMap = (Map<Id, Job_Application__c>) Trigger.newMap;
    }
    
    /**
    * @description Before Insert method.
    **/
    public override void beforeInsert() {
        // Collect Account (Company) Ids to get Contacts
        Set<Id> companies = new Set<Id>();
        for (Job_Application__c jobApp : this.newJobApps) {
            if (jobApp.Primary_Contact__c == null && jobApp.Company_Name__c != null) { 
                companies.add(jobApp.Company_Name__c);
            }
        }
        // Set Primary Contact with the first contact related to the Company
        Map<Id, Id> contactIdByCompanyId = getContactsByAccounts(companies);
        if (contactIdByCompanyId.size() > 0) {
            for (Job_Application__c jobApp : newJobApps) {
                if (jobApp.Primary_Contact__c == null && jobApp.Company_Name__c != null) {
                    jobApp.Primary_Contact__c = contactIdByCompanyId.get(jobApp.Company_Name__c);
                }
            }
        }
    }

    /**
    * @description Before Update method.
    **/
    public override void beforeUpdate() {
        // Collect first Pivotal Contacts
        Map<Id, Id> pivotContIdByJobAppId = getPivotalContactByJobApp(this.newJobAppsMap.keySet());
        // Collect Account (Company) Ids to get Contacts
        Set<Id> companies = new Set<Id>();
        Set<Id> jobAppIdsToUpdate = new Set<Id>();
        // Set Promary Contact with first Contact available in the Pivotal Contacts.
        for (Job_Application__c jobApp : this.newJobAppsMap.values()) {
            if (jobApp.Primary_Contact__c == null) {
                jobApp.Primary_Contact__c = pivotContIdByJobAppId.get(jobApp.Id);
                if (jobApp.Primary_Contact__c == null && jobApp.Company_Name__c != null) {
                    companies.add(jobApp.Company_Name__c);
                    jobAppIdsToUpdate.add(jobApp.Id);
                }
            }
        }
        // Set Primary Contact with the first contact related to the Company
        if (companies.size() > 0) {
            Map<Id, Id> contactIdByCompanyId = getContactsByAccounts(companies);
            for (Id jobAppId : jobAppIdsToUpdate) {
                Job_Application__c jobApp = this.newJobAppsMap.get(jobAppId);
                jobApp.Primary_Contact__c = contactIdByCompanyId.get(jobApp.Company_Name__c);
            }
        }
    }

    /**
    * @description Collect the first related Contact to the Account.
    * @param accounts: Set of Account Ids
    * @return: the Map of the first Contact Id by it's Account Id.
    **/
    private Map<Id, Id> getContactsByAccounts(Set<Id> accounts) {
        Map<Id, Id> contactIdByAccountId = new Map<Id, Id>();
        List<Account> accountsWithContacts = [
            SELECT 
                Id,
                (SELECT Id FROM Contacts LIMIT 1)
            FROM Account
            WHERE Id IN :accounts
        ];
        for (Account acc : accountsWithContacts) {
            if (acc.Contacts.size() > 0) {
                contactIdByAccountId.put(acc.Id, acc.Contacts[0].Id);
            }
        }
        return contactIdByAccountId;
    }

    /**
    * @description Collect the first Pivotal Contact to the Job Application.
    * @param jobAppIds: List of Job Application Ids
    * @return: the Map of the first Pivotal Contact Id by it's Job Application Id.
    **/
    private Map<Id, Id> getPivotalContactByJobApp(Set<Id> jobAppIds) {
        Map<Id, Id> contactIdByJobAppId = new Map<Id, Id>();
        List<Job_Application__c> jobAppWithPivotalCont = [
            SELECT 
                Id, 
                (SELECT Contact__c 
                FROM Pivotal_Contacts__r 
                ORDER BY Name ASC LIMIT 1)
                FROM Job_Application__c
                WHERE Id IN :jobAppIds
        ];
        for (Job_Application__c jobApp : jobAppWithPivotalCont) {
            if (jobApp.Pivotal_Contacts__r.size() > 0) {
                contactIdByJobAppId.put(jobApp.Id, jobApp.Pivotal_Contacts__r[0].Contact__c);
            }
        }
        return contactIdByJobAppId;
    }
}