force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <description>Stores job applications on vacancies. Helps to log and manage the entire job application lifecycle.</description>
    <label>Job Application</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0}</displayFormat>
        <label>Job Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pivotal_Contact__c/Pivotal_Contact__c.object-meta.xml
<CustomObject>
    <description>Helps tracking of pivotal individuals associated with the job application, such as hiring managers, recruiters, and other relevant employees.</description>
    <label>Pivotal Contact</label>
    <nameField>
        <displayFormat>PC# {0}</displayFormat>
        <label>Pivotal Contact Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pivotal Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Pivotal_Contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>The Contact associated with the job application. This could be the hiring manager, recruiter, or other relevant employee.</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Relates to Job Applications</relationshipLabel>
    <relationshipName>Pivotal_Contacts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Pivotal_Contact__c/fields/Job_Application__c.field-meta.xml
<CustomField>
    <fullName>Job_Application__c</fullName>
    <description>Job Application to which contact is related.</description>
    <label>Job Application</label>
    <referenceTo>Job_Application__c</referenceTo>
    <relationshipLabel>Pivotal Contacts</relationshipLabel>
    <relationshipName>Pivotal_Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/JobApplicationHelper.cls
public with sharing class JobApplicationHelper {

    /**
    * @description Collect the first Pivotal Contact to the Job Application.
    * @param jobAppIds: List of Job Application Ids
    * @return: the Map of the first Pivotal Contact Id by it's Job Application Id.
    **/
    public static Map<Id, Id> getPivotalContactByJobApp(Set<Id> jobAppIds) {
        Map<Id, Id> contactIdByJobAppId = new Map<Id, Id>();
        List<Job_Application__c> jobAppWithPivotalCont = [
            SELECT 
                Id, 
                (SELECT Contact__c 
                FROM Pivotal_Contacts__r 
                ORDER BY Name ASC LIMIT 1)
                FROM Job_Application__c
                WHERE Id IN :jobAppIds
        ];
        for (Job_Application__c jobApp : jobAppWithPivotalCont) {
            if (jobApp.Pivotal_Contacts__r.size() > 0) {
                contactIdByJobAppId.put(jobApp.Id, jobApp.Pivotal_Contacts__r[0].Contact__c);
            }
        }
        return contactIdByJobAppId;
    }

    /**
    * @description Runs Queueable class to create Tasks related to the Job Application Status
    * @param jobAppStatusById: Map of the Job Application Statuses by the Job Application Ids
    **/
    public static void addTasksByJobAppStatus(List<Job_Application__c> jobApps, List<String> statuses) {
        JobApplicationTasksQueueable jobAppTasksJob = new JobApplicationTasksQueueable(jobApps, statuses);
        System.enqueueJob(jobAppTasksJob);
    }
}