force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <description>Stores job applications on vacancies. Helps to log and manage the entire job application lifecycle.</description>
    <label>Job Application</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0}</displayFormat>
        <label>Job Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>This field will track the current status of the job application.</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saved</fullName>
                <default>true</default>
                <label>Saved</label>
            </value>
            <value>
                <fullName>Applying</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Interviewing</fullName>
            </value>
            <value>
                <fullName>Negotiating</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Application_Task__mdt/Job_Application_Task__mdt.object-meta.xml
<CustomObject>
    <description>The list of possible Job Application Tasks depending on the current Status of the job application.</description>
    <label>Job Application Task</label>
    <pluralLabel>Job Application Tasks</pluralLabel>
</CustomObject>

force-app/main/default/objects/Job_Application_Task__mdt/fields/Days_untill_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Days_untill_Due_Date__c</fullName>
    <description>Represents the number of days until the due date of the task.</description>
    <label>Days untill Due Date</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Job_Application_Task__mdt/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <description>Indicates the importance or urgency of a task, such as high or low.</description>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
                <default>true</default>
                <label>High</label>
            </value>
            <value>
                <fullName>Normal</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Application_Task__mdt/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The Job Application Statuses. They group Tasks.</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saved</fullName>
                <default>true</default>
                <label>Saved</label>
            </value>
            <value>
                <fullName>Applying</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Interviewing</fullName>
            </value>
            <value>
                <fullName>Negotiating</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Application_Task__mdt/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <description>The subject line of the task.</description>
    <label>Subject</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/JobApplicationTasksQueueable.cls
public class JobApplicationTasksQueueable implements Queueable {

    private List<Job_Application__c> jobApps;
    private Set<String> statusSet = new Set<String>();
    private Map<String, List<Job_Application_Task__mdt>> taskParamsByStatus = new Map<String, List<Job_Application_Task__mdt>>();

    public JobApplicationTasksQueueable(List<Job_Application__c> jobApps, List<String> statuses) {
        this.jobApps = jobApps;
        this.statusSet.addAll(statuses);
    }

    public void execute(QueueableContext context) {
        // Collect Task params to create
        List<Job_Application_Task__mdt> taskParamsToCreate = [
            SELECT 
                Status__c, 
                Priority__c, 
                Days_untill_Due_Date__c, 
                Subject__c 
            FROM Job_Application_Task__mdt 
            WHERE Status__c IN :this.statusSet
        ];

        if (taskParamsToCreate.size() > 0) {
            // Collect Map of Task Params for each Status
            for (Job_Application_Task__mdt tskParam : taskParamsToCreate) {
                if (this.taskParamsByStatus.containsKey(tskParam.Status__c)) {
                    this.taskParamsByStatus.get(tskParam.Status__c).add(tskParam);
                } else {
                    this.taskParamsByStatus.put(tskParam.Status__c, new List<Job_Application_Task__mdt>{tskParam});
                }
            }

            createTasks();
        }
    }

    /**
    * @description Creates Tasks for each Job Application buy Status
    **/
    private void createTasks() {
        List<Task> newTasks = new List<Task>();  
        for (Job_Application__c jobApp : this.jobApps) {
            List<Job_Application_Task__mdt> taskParams = this.taskParamsByStatus.get(jobApp.Status__c);
            for (Job_Application_Task__mdt param : taskParams) {
                Task newTask = new Task();
                newTask.Subject = param.Subject__c;
                newTask.ActivityDate = Date.today().addDays((Integer)param.Days_untill_Due_Date__c);
                newTask.WhatId = jobApp.Id;
                newTask.OwnerId = jobApp.OwnerId;
                newTask.Priority = param.Priority__c;
                newTasks.add(newTask);
            }
        }
        Database.insert(newTasks);
    }
}