force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <description>Stores job applications on vacancies. Helps to log and manage the entire job application lifecycle.</description>
    <label>Job Application</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0}</displayFormat>
        <label>Job Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Holds detailed information about the job, such as responsibilities, qualifications, benefits, etc.</description>
    <label>Description</label>
    <length>100000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Represents the main point of contact for the job. This could be a recruiter or employee at the company.</description>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pivotal_Contact__c/Pivotal_Contact__c.object-meta.xml
<CustomObject>
    <description>Helps tracking of pivotal individuals associated with the job application, such as hiring managers, recruiters, and other relevant employees.</description>
    <label>Pivotal Contact</label>
    <nameField>
        <displayFormat>PC# {0}</displayFormat>
        <label>Pivotal Contact Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pivotal Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Pivotal_Contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>The Contact associated with the job application. This could be the hiring manager, recruiter, or other relevant employee.</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Relates to Job Applications</relationshipLabel>
    <relationshipName>Pivotal_Contacts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Pivotal_Contact__c/fields/Job_Application__c.field-meta.xml
<CustomField>
    <fullName>Job_Application__c</fullName>
    <description>Job Application to which contact is related.</description>
    <label>Job Application</label>
    <referenceTo>Job_Application__c</referenceTo>
    <relationshipLabel>Pivotal Contacts</relationshipLabel>
    <relationshipName>Pivotal_Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/JobApplicationTriggerHandlerHelperTest.cls
/**
* JobApplicationTriggerHandlerHelperTest class description:
*
* Test class for the classes JobApplicationTriggerHandler and JobApplicationHelper.
*
**/
@isTest
private class JobApplicationTriggerHandlerHelperTest {

    @TestSetup
    static void makeTestData(){
        Account acc = TestDataFactory.createAccount();
        List<Contact> conts = new List<Contact>();
        for (Integer i = 0; i < 10; i++) {
            Contact cont = new Contact(
                LastName='Test Contact '+i, 
                AccountId=acc.Id
                );
                conts.add(cont);
            }
        Database.insert(conts);
        TestDataFactory.createJobApplication(acc);
    }

    @isTest
    static void testBeforeInsertSetCompanyContactAsPrimaryContact() {
        // Test data were created
        // Assert
        Job_Application__c insertedJobApp = [
            SELECT 
                Id,
                Primary_Contact__c,
                Primary_Contact__r.Name
            FROM Job_Application__c 
            LIMIT 1
        ];
        Id insertedContId = insertedJobApp.Primary_Contact__c;
        Assert.isNotNull(insertedContId, 'Primary Contact should not be Null');
        Assert.areEqual('Test Contact 0', insertedJobApp.Primary_Contact__r.Name, 'Expected to get the first Contact (sorted by Name)');
    }

    @isTest
    static void testBeforeUpdateSetCompanyContactAsPrimaryContact() {
        // Set up test data
        Job_Application__c jobApp = [
            SELECT 
                Id,
                Primary_Contact__c,
                Description__c
            FROM Job_Application__c 
            LIMIT 1
        ];
        
        // Run Test
        Test.startTest();
        jobApp.Primary_Contact__c = null;
        jobApp.Description__c = 'Primary Contact Was Deleted';
        Database.update(jobApp);
        Test.stopTest();

        // Assert
        Job_Application__c updatedJobApp = [
            SELECT 
                Id,
                Primary_Contact__c,
                Description__c
            FROM Job_Application__c 
            WHERE Id = :jobApp.Id
        ];
        Id updatedContId = updatedJobApp.Primary_Contact__c;
        Assert.isNotNull(updatedContId, 'Primary Contact should not be Null');
        Assert.areEqual('Primary Contact Was Deleted', updatedJobApp.Description__c, 'Descriptions should be updated.');
        Contact resCont = [
            SELECT
                Id,
                Name
            FROM Contact
            WHERE Id = :updatedContId
        ];
        Assert.areEqual('Test Contact 0', resCont.Name, 'Expected to get the first Contact (sorted by Name)');
    }

    @isTest
    static void testBeforeUpdateSetPivotalContactAsPrimaryContact() {
        // Set up test data
        Job_Application__c jobApp = [
            SELECT 
                Id,
                Primary_Contact__c,
                Description__c
            FROM Job_Application__c 
            LIMIT 1
        ];
        List<Contact> conts = [SELECT Id FROM Contact];
        List<Pivotal_Contact__c> pivConts = new List<Pivotal_Contact__c>();
        for (Contact cont : conts) {
            Pivotal_Contact__c pivCont = new Pivotal_Contact__c(
                Job_Application__c = jobApp.Id,
                Contact__c = cont.Id
            );
            pivConts.add(pivCont);
        }
        Database.insert(pivConts);
        
        // Run Test
        Test.startTest();
        jobApp.Primary_Contact__c = null;
        jobApp.Description__c = 'Primary Contact Was Deleted';
        Database.update(jobApp);
        Test.stopTest();

        // Assert
        Job_Application__c updatedJobApp = [
            SELECT 
                Id,
                Primary_Contact__c,
                Description__c
            FROM Job_Application__c 
            WHERE Id = :jobApp.Id
        ];
        Id updatedContId = updatedJobApp.Primary_Contact__c;
        Assert.isNotNull(updatedContId, 'Primary Contact should not be Null');
        Assert.areEqual('Primary Contact Was Deleted', updatedJobApp.Description__c, 'Descriptions should be updated.');
        Pivotal_Contact__c resCont = [
            SELECT 
                Contact__r.Name
            FROM Pivotal_Contact__c
            WHERE Job_Application__c = :updatedJobApp.Id
                AND Contact__c = :updatedContId
            ORDER BY Name ASC 
            LIMIT 1
        ];
        Assert.areEqual('Test Contact 0', resCont.Contact__r.Name, 'Expected to get the first Contact (sorted by Name)');
    }
}